apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
spec:
  secretName: wisecow-tls-secret
  issuerRef:
    name: letsencrypt-issuer
  commonName: wisecow.github.io
  dnsNames:
    - wisecow.github.io
